export const projectList = [
  {
    projectName: "Book Search Engine",
    projectUrl: "https://booksearch-engine.onrender.com/",
    projectDescription: "MERN",
    imageUrl: "/booksearch.png",
    projectGithub: "https://github.com/WesleyHAS/booksearch-engine",
  },
  {
    projectName: "React Portfolio",
    projectUrl: "https://wesleyhas.netlify.app/",
    projectDescription: "React",
    imageUrl: "/reactporfolio.png",
    projectGithub: "https://github.com/WesleyHAS/weshas-portfolio",
  },
  {
    projectName: "Tech Blog",
    projectUrl: "https://rainbowtrout14-c7e64305977c.herokuapp.com/",
    projectDescription: "Interactive Full-Stack MVC",
    imageUrl: "/tech-blog2.png",
    projectGithub: "https://github.com/WesleyHAS/tech-blog",
  },
  {
    projectName: "Redux E-Commerce",
    projectUrl: "https://redux-ecommerce.onrender.com/",
    projectDescription: "State Management with Redux",
    imageUrl: "/redux-ecommerce.png",
    projectGithub: "https://github.com/WesleyHAS/redux-ecommerce",
  },
  {
    projectName: "J.A.T.E Text Editor",
    projectUrl: "https://github.com/WesleyHAS/pwa_texteditor",
    projectDescription: "Progressive Web Applications (PWA)",
    imageUrl: "/jate-pwa.png",
    projectGithub: "https://github.com/WesleyHAS/pwa_texteditor",
  },
  {
    projectName: "Horiseon Web Expertise",
    projectUrl: "https://wesleyhas.github.io/horiseon-web-expertise/",
    projectDescription: "CSS",
    imageUrl: "/horiseon.png",
    projectGithub: "https://github.com/WesleyHAS/horiseon-web-expertise",
  },
  {
    projectName: "Weather Dashboard",
    projectUrl: "https://wesleyhas.github.io/weather-dashboard-project/",
    projectDescription: "Server-Side API",
    imageUrl: "/weather-dashboard.png",
    projectGithub: "https://github.com/WesleyHAS/weather-dashboard-project",
  },
  {
    projectName: "Note Taker",
    projectUrl: "https://pacific-sea-55121-e1e3f466f860.herokuapp.com/",
    projectDescription: "ExpressJS",
    imageUrl: "/note-taker.png",
    projectGithub: "https://github.com/WesleyHAS/note-taker",
  },
  {
    projectName: "Code Quiz",
    projectUrl: "https://wesleyhas.github.io/code-quiz-project/",
    projectDescription: "Web APIs",
    imageUrl: "/code-quiz2.png",
    projectGithub: "https://github.com/WesleyHAS/code-quiz-project",
  },
  {
    projectName: "Daily Planner",
    projectUrl: "https://wesleyhas.github.io/daily-planner-project/",
    projectDescription: "Third-Party API",
    imageUrl: "/daily-planner.png",
    projectGithub: "https://github.com/WesleyHAS/daily-planner-project",
  },
  {
    projectName: "Password Generator",
    projectUrl: "https://wesleyhas.github.io/password-generator-project/",
    projectDescription: "Vanilla JS",
    imageUrl: "/pw-generator.png",
    projectGithub: "https://github.com/WesleyHAS/password-generator-project",
  },
  {
    projectName: "Simple Portfolio",
    projectUrl: "https://wesleyhas.github.io/personal-portfolio-project/",
    projectDescription: "HTML/CSS",
    imageUrl: "/simple-portfolio.png",
    projectGithub: "https://github.com/WesleyHAS/personal-portfolio-project",
  },
  {
    projectName: "Pre-Work Study Guide",
    projectUrl: "https://wesleyhas.github.io/prework-study-guide/",
    projectDescription: "HTML/CSS",
    imageUrl: "/prework-studyguide.png",
    projectGithub: "https://github.com/WesleyHAS/prework-study-guide",
  },
];
